# Generated by Django 2.2 on 2019-04-06 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=240, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('version', models.CharField(blank=True, default='1.0', max_length=15, null=True, unique=True)),
                ('technology', models.CharField(blank=True, choices=[('-', 'Technology'), ('flask', 'Flask - Python'), ('django', 'Django - Python'), ('drf', 'Django Rest Framework - Python'), ('django_drf', 'Django With Django Rest Framework - Python'), ('apistar', 'Apistar - Python'), ('plain_php', 'Plan PHP - PHP'), ('plain_php_7', 'Plan PHP 7 - PHP'), ('mamp_php', 'MAMP - PHP'), ('lamp_php', 'LAMP - PHP'), ('slim_php', 'Slim PHP - PHP'), ('ci_php', 'CodeIgniter - PHP'), ('symfony', 'Symfony - PHP'), ('yii', 'Yii - PHP'), ('yii_2', 'Yii 2 - PHP'), ('wp', 'WordPress - PHP'), ('buffalo-go', 'Buffalo - Go'), ('mean-js', 'MEAN - JavaScript'), ('apollo-server-js', 'Apollo Server - JavaScript'), ('parse-js', 'Parse - JavaScript')], default='-', max_length=200, null=True)),
                ('stack', models.BooleanField(default=False)),
                ('db_engine', models.CharField(blank=True, choices=[('-', 'Database'), ('postgres', 'PostgreSQL'), ('mysql', 'MySql'), ('mariadb', 'MariaDB'), ('sqlite', 'SQLite')], default='-', max_length=200, null=True)),
                ('db_name', models.CharField(blank=True, max_length=180, null=True)),
                ('db_dump', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('git_repo', models.TextField(blank=True, null=True)),
                ('dockerized', models.BooleanField(default=False)),
                ('admin_panel', models.BooleanField(blank=True, default=False)),
                ('product', models.CharField(blank=True, choices=[('-', 'Product'), ('rest', 'REST'), ('soap', 'SOAP'), ('websocket', 'WebSocket'), ('e-commerce', 'E-Commerce'), ('e-commerce-api', 'E-commerce API'), ('blog', 'Blog'), ('blog-api', 'Blog API'), ('personal-page', 'Personal Page')], default='-', max_length=200)),
                ('output', models.CharField(blank=True, choices=[('-', 'Output Data Format'), ('json', 'JSON'), ('xml', 'XML'), ('yalm', 'YALM')], default='-', max_length=200, null=True)),
                ('request_log', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app_creator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'app',
                'verbose_name_plural': 'apps',
            },
        ),
    ]
