# Generated by Django 2.0 on 2018-03-01 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='admin_panel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='app',
            name='db_dump',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='app',
            name='db_engine',
            field=models.CharField(blank=True, choices=[('postgres', 'PostgreSQL'), ('mysql', 'MySql'), ('mariadb', 'MariaDB'), ('sqlite', 'SQLite')], default='postgres', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='app',
            name='db_name',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
        migrations.AddField(
            model_name='app',
            name='dockerized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='app',
            name='git_repo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='app',
            name='output',
            field=models.CharField(blank=True, choices=[('json', 'JSON'), ('yalm', 'YALM')], default='json', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='app',
            name='request_log',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='app',
            name='stack',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='app',
            name='technology',
            field=models.CharField(blank=True, choices=[('rest', 'REST'), ('soap', 'SOAP'), ('websocket', 'WebSocket'), ('e-commerce', 'E-Commerce'), ('e-commerce-api', 'E-commerce API'), ('blog', 'Blog'), ('blog-api', 'Blog API'), ('personal-page', 'Personal Page')], default='rest', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='app',
            name='version',
            field=models.CharField(blank=True, default='1.0', max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='app',
            name='app_name',
            field=models.CharField(max_length=240, unique=True),
        ),
    ]
