# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-02 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='product',
            field=models.CharField(blank=True, choices=[('rest', 'REST'), ('soap', 'SOAP'), ('websocket', 'WebSocket'), ('e-commerce', 'E-Commerce'), ('e-commerce-api', 'E-commerce API'), ('blog', 'Blog'), ('blog-api', 'Blog API'), ('personal-page', 'Personal Page')], default='rest', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='app',
            name='technology',
            field=models.CharField(blank=True, choices=[('python', 'Python'), ('-', '------'), ('flask', 'Flask'), ('django', 'Django'), ('drf', 'Django Rest Framework'), ('django_drf', 'Django With Django Rest Framework'), ('apistar', 'Apistar'), ('php', 'PHP'), ('-', '------'), ('plain_php', 'Plan PHP'), ('plain_php_7', 'Plan PHP 7'), ('slim_php', 'Slim PHP'), ('ci_php', 'CodeIgniter'), ('symfony', 'Symfony'), ('yii', 'Yii'), ('yii_2', 'Yii 2'), ('wp', 'WordPress'), ('go', 'Go'), ('-', '------'), ('js', 'JavaScript'), ('-', '------')], default='flask', max_length=200, null=True),
        ),
    ]
