# Generated by Django 2.2 on 2019-04-06 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='db_dump',
        ),
    ]
