# Generated by Django 2.2 on 2019-04-06 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_remove_app_db_dump'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='db_dump',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
