# Generated by Django 2.2 on 2019-04-06 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_app_db_dump'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='version',
            field=models.CharField(blank=True, default='1.0', max_length=15, null=True),
        ),
    ]
