# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-02 01:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_auto_20180301_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='db_engine',
            field=models.CharField(blank=True, choices=[('-', 'Database'), ('postgres', 'PostgreSQL'), ('mysql', 'MySql'), ('mariadb', 'MariaDB'), ('sqlite', 'SQLite')], default='-', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='app',
            name='output',
            field=models.CharField(blank=True, choices=[('-', 'Output Data Format'), ('json', 'JSON'), ('xml', 'XML'), ('yalm', 'YALM')], default='-', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='app',
            name='product',
            field=models.CharField(blank=True, choices=[('-', 'Product'), ('rest', 'REST'), ('soap', 'SOAP'), ('websocket', 'WebSocket'), ('e-commerce', 'E-Commerce'), ('e-commerce-api', 'E-commerce API'), ('blog', 'Blog'), ('blog-api', 'Blog API'), ('personal-page', 'Personal Page')], default='-', max_length=200),
        ),
    ]
