# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-21 02:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apps', '0007_auto_20180301_1953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='app',
            old_name='is_active',
            new_name='active',
        ),
        migrations.RemoveField(
            model_name='app',
            name='date_created',
        ),
        migrations.AddField(
            model_name='app',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='app',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='app',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
