# Generated by Django 2.1.7 on 2019-03-21 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_auto_20190320_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='admin_panel',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='app',
            name='technology',
            field=models.CharField(blank=True, choices=[('-', 'Technology'), ('flask', 'Flask - Python'), ('django', 'Django - Python'), ('drf', 'Django Rest Framework - Python'), ('django_drf', 'Django With Django Rest Framework - Python'), ('apistar', 'Apistar - Python'), ('plain_php', 'Plain PHP - PHP'), ('plain_php_7', 'Plain PHP 7 - PHP'), ('mamp_php', 'MAMP - PHP'), ('lamp_php', 'LAMP - PHP'), ('slim_php', 'Slim PHP - PHP'), ('ci_php', 'CodeIgniter - PHP'), ('symfony', 'Symfony - PHP'), ('yii', 'Yii - PHP'), ('yii_2', 'Yii 2 - PHP'), ('wp', 'WordPress - PHP'), ('buffalo-go', 'Buffalo - Go'), ('mean-js', 'MEAN - JavaScript'), ('apollo-server-js', 'Apollo Server - JavaScript'), ('parse-js', 'Parse - JavaScript')], default='-', max_length=200, null=True),
        ),
    ]
